{
  "openapi": "3.0.3",
  "info": {
    "title": "Wiseinf Management OpenAPI 1.0.0",
    "description": "Wiseinf Management OpenAPI provides a set of API for management.",
    "termsOfService": "http://www.wiseinf.com/terms/",
    "contact": {
      "email": "business@wiseinf.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://management.wiseinf.com/api/v1"
    }
  ],
  "tags": [
    {
      "name": "cluster",
      "description": "Cluster"
    },
    {
      "name": "cloud provider",
      "description": "Cloud Provider"
    },
    {
      "name": "label",
      "description": "Label"
    },
    {
      "name": "alicloud",
      "description": "Operations about alibaba cloud"
    },
    {
      "name": "aws",
      "description": "Operations about amazon aws cloud"
    },
    {
      "name": "huawei cloud",
      "description": "Operations about huawei cloud"
    },
    {
      "name": "version",
      "description": "Operations about version"
    }
  ],
  "paths": {
    "/management/clusters": {
      "post": {
        "tags": [
          "cluster"
        ],
        "summary": "Create or import a cluster.",
        "description": "Import a cluster.",
        "operationId": "importCluster",
        "security": [
          {
            "auth": [
              "write:wiseinf",
              "read:wiseinf"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "cluster"
        ],
        "summary": "Get cluster configs.",
        "description": "Get cluster configs.",
        "operationId": "getClusterConfigs",
        "security": [
          {
            "auth": [
              "write:wiseinf",
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/clusters/{clusterId}": {
      "get": {
        "tags": [
          "cluster"
        ],
        "summary": "Get cluster config.",
        "description": "Multiple status values can be provided with comma separated strings",
        "operationId": "getClusterConfig",
        "security": [
          {
            "auth": [
              "write:wiseinf",
              "read:wiseinf"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "cluster"
        ],
        "summary": "Create or import a cluster.",
        "description": "Get cost of clusters.",
        "operationId": "updateCluster",
        "security": [
          {
            "auth": [
              "write:wiseinf",
              "read:wiseinf"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "cluster"
        ],
        "summary": "Create or import a cluster.",
        "description": "Get cost of clusters.",
        "operationId": "deleteClusterConfig",
        "security": [
          {
            "auth": [
              "write:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/labels": {
      "put": {
        "tags": [
          "label"
        ],
        "summary": "Update labels.",
        "description": "Update labels.",
        "operationId": "updateLabels",
        "security": [
          {
            "auth": [
              "write:wiseinf",
              "read:wiseinf"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "label"
        ],
        "summary": "Get labels.",
        "description": "Get labels.",
        "operationId": "getLabels",
        "security": [
          {
            "auth": [
              "write:wiseinf",
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/cloudproviders": {
      "post": {
        "tags": [
          "cloud provider"
        ],
        "summary": "Create or import a cloud provider.",
        "description": "Create or import a cloud provider.",
        "operationId": "importCloudProvider",
        "security": [
          {
            "auth": [
              "write:wiseinf",
              "read:wiseinf"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "cloud provider"
        ],
        "summary": "Get cloud provider.",
        "description": "Get cloud provider.",
        "operationId": "getCloudProviders",
        "security": [
          {
            "auth": [
              "write:wiseinf",
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/cloudproviders/{providerId}": {
      "get": {
        "tags": [
          "cloud provider"
        ],
        "summary": "Get a cloud provider.",
        "description": "Get a cloud provider.",
        "operationId": "getCloudProvider",
        "security": [
          {
            "auth": [
              "write:wiseinf",
              "read:wiseinf"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "cloud provider"
        ],
        "summary": "Update a cloud provider.",
        "description": "Update a cloud provider.",
        "operationId": "updateCloudProvider",
        "security": [
          {
            "auth": [
              "write:wiseinf",
              "read:wiseinf"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "cloud provider"
        ],
        "summary": "Delete a cloud provider.",
        "description": "Delete a cloud provider.",
        "operationId": "deleteCloudProvider",
        "security": [
          {
            "auth": [
              "write:wiseinf",
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/cloudproviders/{providerId}/connectivity": {
      "post": {
        "tags": [
          "cloud provider"
        ],
        "summary": "test a connectivity of a new cloud provider, the cloud provider's config is not saved.",
        "description": "Test  a cloud provider.",
        "operationId": "testCloudProviderConnectivityOnTheFly",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "cloud provider"
        ],
        "summary": "test a connectivity of a existing cloud provider.",
        "description": "Get a cloud provider.",
        "operationId": "testCloudProviderConnectivity",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/aliyun/regions": {
      "get": {
        "tags": [
          "alicloud"
        ],
        "summary": "get regions of aliyun.",
        "description": "get regions of aliyun.",
        "operationId": "getAliyunRegions"
      }
    },
    "/management/import/aliyun/validateAccessToken": {
      "post": {
        "tags": [
          "alicloud"
        ],
        "summary": "validate a connectivity of a new cloud provider, the cloud provider's config is not saved.",
        "description": "Test  a cloud provider.",
        "operationId": "validateAccessToken",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/aliyun/managedClusters": {
      "post": {
        "tags": [
          "alicloud"
        ],
        "summary": "get managed kubernetes clusters of alibaba cloud.",
        "description": "get managed kubernetes clusters of alibaba cloud.",
        "operationId": "getAliyunManagedClusters",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/aliyun/kubeconfig": {
      "post": {
        "tags": [
          "alicloud"
        ],
        "summary": "get kubeconfig of a managed kubernetes cluster.",
        "description": "get kubeconfig of a managed kubernetes cluster.",
        "operationId": "getAliyunKubeConfig",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/aliyun/validateKubeconfig": {
      "post": {
        "tags": [
          "alicloud"
        ],
        "summary": "validate kubeconfig of a managed kubernetes cluster.",
        "description": "validate kubeconfig of a managed kubernetes cluster.",
        "operationId": "validateAliyunKubeConfig",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/aliyun/validatePrometheusConfig": {
      "post": {
        "tags": [
          "alicloud"
        ],
        "summary": "validate prometheus config of a managed kubernetes cluster.",
        "description": "validate prometheus config  of a managed kubernetes cluster.",
        "operationId": "validateAlibabaCloudPrometheusConfig",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/aws/regions": {
      "get": {
        "tags": [
          "aws"
        ],
        "summary": "get regions of amazon aws.",
        "description": "get regions of amazon aws.",
        "operationId": "getAWSRegions"
      }
    },
    "/management/import/aws/validateAccessToken": {
      "post": {
        "tags": [
          "aws"
        ],
        "summary": "validate a connectivity of a new cloud provider, the cloud provider's config is not saved.",
        "description": "Test a cloud provider.",
        "operationId": "validateAWSAccessToken",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/aws/managedClusters": {
      "post": {
        "tags": [
          "aws"
        ],
        "summary": "get managed kubernetes clusters of aws.",
        "description": "get managed kubernetes clusters of aws.",
        "operationId": "getAWSManagedClusters",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/aws/kubeconfig": {
      "post": {
        "tags": [
          "aws"
        ],
        "summary": "get kubeconfig of a managed kubernetes cluster.",
        "description": "get kubeconfig of a managed kubernetes cluster.",
        "operationId": "getAWSKubeConfig",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/aws/validateKubeconfig": {
      "post": {
        "tags": [
          "aws"
        ],
        "summary": "validate kubeconfig of a managed kubernetes cluster.",
        "description": "validate kubeconfig of a managed kubernetes cluster.",
        "operationId": "validateAWSKubeConfig",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/aws/validatePrometheusConfig": {
      "post": {
        "tags": [
          "aws"
        ],
        "summary": "validate prometheus config of a managed kubernetes cluster.",
        "description": "validate prometheus config  of a managed kubernetes cluster.",
        "operationId": "validateAWSPrometheusConfig",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/huaweicloud/regions": {
      "get": {
        "tags": [
          "huawei cloud"
        ],
        "summary": "get regions of huawei cloud.",
        "description": "get regions of huawei cloud.",
        "operationId": "getHuaweiCloudRegions"
      }
    },
    "/management/import/huaweicloud/validateAccessToken": {
      "post": {
        "tags": [
          "huawei cloud"
        ],
        "summary": "validate a connectivity of a new cloud provider, the cloud provider's config is not saved.",
        "description": "Test a cloud provider.",
        "operationId": "validateHuaweiCloudAccessToken",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/huaweicloud/managedClusters": {
      "post": {
        "tags": [
          "huawei cloud"
        ],
        "summary": "get managed kubernetes clusters of huawei cloud.",
        "description": "get managed kubernetes clusters of huawei cloud.",
        "operationId": "getHuaweiCloudManagedClusters",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/huaweicloud/kubeconfig": {
      "post": {
        "tags": [
          "huawei cloud"
        ],
        "summary": "get kubeconfig of a managed kubernetes cluster.",
        "description": "get kubeconfig of a managed kubernetes cluster.",
        "operationId": "getHuaweiCloudKubeConfig",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/huaweicloud/validateKubeconfig": {
      "post": {
        "tags": [
          "huawei cloud"
        ],
        "summary": "validate kubeconfig of a managed kubernetes cluster.",
        "description": "validate kubeconfig of a managed kubernetes cluster.",
        "operationId": "validateHuaweiCloudKubeConfig",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/import/huaweicloud/validatePrometheusConfig": {
      "post": {
        "tags": [
          "huawei cloud"
        ],
        "summary": "validate prometheus config of a managed kubernetes cluster.",
        "description": "validate prometheus config of a managed kubernetes cluster.",
        "operationId": "validateHuaweiCloudPrometheusConfig",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      }
    },
    "/management/notification/channels": {
      "post": {
        "tags": [
          "notification channel"
        ],
        "summary": "create a new notification channel.",
        "description": "create a new notification channel.",
        "operationId": "createNotificationChannel",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "notification channel"
        ],
        "summary": "list notification channels.",
        "description": "list notification channels.",
        "operationId": "listNotificationChannels"
      }
    },
    "/management/notification/channels/{channelName}": {
      "put": {
        "tags": [
          "notification channel"
        ],
        "summary": "update a existing notification channel.",
        "description": "update a existing  notification channel.",
        "operationId": "updateNotificationChannel",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "notification channel"
        ],
        "summary": "get notification channel.",
        "description": "get notification channel.",
        "operationId": "getNotificationChannel"
      },
      "delete": {
        "tags": [
          "notification channel"
        ],
        "summary": "delete notification channel.",
        "description": "delete notification channel.",
        "operationId": "deleteNotificationChannel"
      }
    },
    "/management/notification/channels/{channelName}/connectivity": {
      "put": {
        "tags": [
          "notification channel"
        ],
        "summary": "test connectivity of a notification channel according to body content.",
        "description": "test connectivity of a notification channel according to body content.",
        "operationId": "testNotificationChannelConnectivity",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "notification channel"
        ],
        "summary": "test connectivity of an existing notification channel.",
        "description": "test connectivity of an existing  notification channel.",
        "operationId": "testExistingNotificationChannelConnectivity"
      }
    },
    "/management/notification/rules": {
      "post": {
        "tags": [
          "notification rule"
        ],
        "summary": "create a new notification rule.",
        "description": "create a new notification rule.",
        "operationId": "createNotificationRule",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "notification rule"
        ],
        "summary": "list notification rules.",
        "description": "list notification rules.",
        "operationId": "listNotificationRules"
      }
    },
    "/management/notification/rules/{ruleName}": {
      "put": {
        "tags": [
          "notification rule"
        ],
        "summary": "update a existing notification rule.",
        "description": "update a existing  notification rule.",
        "operationId": "updateNotificationRule",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "notification rule"
        ],
        "summary": "get a notification rule.",
        "description": "get a notification rule.",
        "operationId": "getNotificationRule"
      },
      "delete": {
        "tags": [
          "notification rule"
        ],
        "summary": "delete notification rule.",
        "description": "list notification rule.",
        "operationId": "deleteNotificationRule"
      }
    },
    "/management/cluster/accessAccounts": {
      "get": {
        "tags": [
          "cluster access account"
        ],
        "summary": "get cluster access accounts for current user.",
        "description": "get cluster access accounts for current user.",
        "operationId": "getClusterAccessAccounts"
      },
      "delete": {
        "tags": [
          "cluster access account"
        ],
        "summary": "delete current user's cluster access accounts.",
        "description": "delete current user's cluster access accounts.",
        "operationId": "deleteClusterAccessAccounts"
      }
    },
    "/management/cluster/accessAccounts/{clusterId}": {
      "post": {
        "tags": [
          "cluster access account"
        ],
        "summary": "create a cluster access account.",
        "description": "create a cluster access account.",
        "operationId": "createClusterAccessAccount",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "cluster access account"
        ],
        "summary": "update an existing cluster access account.",
        "description": "update an existing cluster access account.",
        "operationId": "updateClusterAccessAccount",
        "security": [
          {
            "auth": [
              "read:wiseinf"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "cluster access account"
        ],
        "summary": "get a cluster access account.",
        "description": "get a cluster access account.",
        "operationId": "getClusterAccessAccount"
      },
      "delete": {
        "tags": [
          "cluster access account"
        ],
        "summary": "delete a cluster access account.",
        "description": "delete a cluster access account.",
        "operationId": "deleteClusterAccessAccount"
      }
    },
    "/systeminfo": {
      "get": {
        "tags": [
          "systeminfo"
        ],
        "description": "获取当前系统信息",
        "operationId": "getSystemInfo"
      }
    },
    "/management/accesskeys": {
      "get": {
        "tags": [
          "access key"
        ],
        "summary": "List access keys of current user.",
        "description": "List access keys",
        "operationId": "listAccessKeys"
      },
      "post": {
        "tags": [
          "access key"
        ],
        "summary": "Create an access key.",
        "description": "Create an access key.",
        "operationId": "createAccessKey"
      }
    },
    "/management/accesskeys/{keyId}": {
      "get": {
        "tags": [
          "access key"
        ],
        "summary": "Get access key.",
        "description": "Get access key.",
        "operationId": "getAccessKey"
      },
      "delete": {
        "tags": [
          "access key"
        ],
        "summary": "Delete an access key.",
        "description": "Delete an access key.",
        "operationId": "deleteAccessKey"
      }
    },
    "/management/accesskeys/{keyId}/disable": {
      "put": {
        "tags": [
          "access key"
        ],
        "summary": "Disable access key.",
        "description": "Disable access key.",
        "operationId": "disableAccessKey"
      }
    },
    "/management/accesskeys/{keyId}/enable": {
      "put": {
        "tags": [
          "access key"
        ],
        "summary": "Enable access key.",
        "description": "Enable access key.",
        "operationId": "enableAccessKey"
      }
    },
    "/version": {
      "get": {
        "tags": [
          "version"
        ],
        "description": "获取当前系统版本",
        "operationId": "getVersion"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "auth": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://www.wiseinf.com/oauth/authorize",
            "scopes": {
              "write:wiseinf": "write permission for wiseinf",
              "read:wiseinf": "read permission for wiseinf",
              "admin:wiseinf": "admin permission for wiseinf"
            }
          }
        }
      },
      "api_key": {
        "type": "apiKey",
        "name": "api_key",
        "in": "header"
      }
    }
  }
}