{
  "openapi": "3.0.3",
  "info": {
    "title": "Wiseinf Wisecost OpenAPI 1.0.0",
    "description": "Wiseinf Wisecost OpenAPI provides a set of API for cost monitoring, management and optimize.",
    "termsOfService": "http://www.wiseinf.com/terms/",
    "contact": {
      "email": "wisecost@wiseinf.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://cost.wiseinf.com/api/v1"
    }
  ],
  "tags": [
    {
      "name": "cost",
      "description": "Cost"
    },
    {
      "name": "optimize",
      "description": "Optimize"
    },
    {
      "name": "cluster",
      "description": "Cluster"
    },
    {
      "name": "application",
      "description": "Application"
    },
    {
      "name": "config",
      "description": "Operations about user & configs"
    }
  ],
  "paths": {
    "/api/currentUser": {
      "get": {
        "tags": [
          "user"
        ],
        "description": "获取当前的用户",
        "operationId": "getCurrentUser"
      }
    },
    "/api/logout": {
      "post": {
        "description": "登录接口",
        "operationId": "logout",
        "tags": [
          "login"
        ]
      }
    },
    "/api/login": {
      "post": {
        "tags": [
          "login"
        ],
        "description": "登录接口",
        "operationId": "login"
      }
    },
    "/cost": {
      "get": {
        "tags": [
          "cost"
        ],
        "summary": "Get costs.",
        "description": "Get costs.",
        "operationId": "getCosts"
      }
    },
    "/cluster/breakdown": {
      "get": {
        "tags": [
          "cost"
        ],
        "summary": "Get cost of clusters.",
        "description": "Get cost of clusters.",
        "operationId": "getClusterBreakdowns"
      }
    },
    "/cluster": {
      "get": {
        "tags": [
          "cost"
        ],
        "summary": "Get cost of clusters.",
        "description": "Get cost of clusters.",
        "operationId": "getClusterCosts"
      }
    },
    "/node/breakdown": {
      "get": {
        "tags": [
          "cost"
        ],
        "summary": "Get cost of nodes.",
        "description": "Get cost of nodes.",
        "operationId": "getNodeBreakdowns"
      }
    },
    "/node": {
      "get": {
        "tags": [
          "cost"
        ],
        "summary": "Get cost of nodes.",
        "description": "Get cost of nodes.",
        "operationId": "getNodeCosts"
      }
    },
    "/clusters/{clusterId}/nodes": {
      "get": {
        "tags": [
          "node"
        ],
        "summary": "Get cluster's nodes.",
        "description": "Get cluster's nodes according to clusterId.",
        "operationId": "getClusterNodes",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/clusters/{clusterId}/nodes/{nodeName}": {
      "get": {
        "tags": [
          "node"
        ],
        "summary": "Get cluster's nodes.",
        "description": "Get cluster's nodes according to clusterId.",
        "operationId": "getClusterNode",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/optimize/resource/recommendations": {
      "get": {
        "tags": [
          "optimize"
        ],
        "summary": "Get resource recommendations.",
        "description": "Get resource recommendations.",
        "operationId": "getResourceRecommendations"
      }
    },
    "/optimize/resource/noquotas": {
      "get": {
        "tags": [
          "optimize"
        ],
        "summary": "Get resource no quotas.",
        "description": "Get resource no quotas.",
        "operationId": "getResourceNoQuotas"
      }
    },
    "/optimize/node/lowutilizationrate": {
      "get": {
        "tags": [
          "optimize"
        ],
        "summary": "Get nodes with low utilization rate.",
        "description": "Get  nodes with low utilization rate.",
        "operationId": "getLowUtilizationRateNodes"
      }
    },
    "/optimize/app/oom": {
      "get": {
        "tags": [
          "optimize"
        ],
        "summary": "Get oom events.",
        "description": "Get oom events.",
        "operationId": "getOOMEvents"
      }
    },
    "/management/clusters": {
      "post": {
        "tags": [
          "management",
          "cluster"
        ],
        "summary": "Create or import a cluster.",
        "description": "Get cost of clusters.",
        "operationId": "importCluster",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "management",
          "cluster"
        ],
        "summary": "Get cluster configs.",
        "description": "Get cluster configs.",
        "operationId": "getClusterConfigs",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/clusters/{clusterId}": {
      "get": {
        "tags": [
          "management",
          "cluster"
        ],
        "summary": "Get cluster config.",
        "description": "Multiple status values can be provided with comma separated strings",
        "operationId": "getClusterConfig",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "management",
          "cluster"
        ],
        "summary": "Create or import a cluster.",
        "description": "Get cost of clusters.",
        "operationId": "updateCluster",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "management",
          "cluster"
        ],
        "summary": "Create or import a cluster.",
        "description": "Get cost of clusters.",
        "operationId": "deleteClusterConfig",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/labels": {
      "put": {
        "tags": [
          "management",
          "label"
        ],
        "summary": "Update labels.",
        "description": "Update labels.",
        "operationId": "updateLabels",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "management",
          "label"
        ],
        "summary": "Get labels.",
        "description": "Get labels.",
        "operationId": "getLabels",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/cloudproviders": {
      "post": {
        "tags": [
          "management",
          "cloud provider"
        ],
        "summary": "Create or import a cloud provider.",
        "description": "Create or import a cloud provider.",
        "operationId": "importCloudProvider",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "management",
          "cloud provider"
        ],
        "summary": "Get cloud provider.",
        "description": "Get cloud provider.",
        "operationId": "getCloudProviders",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/cloudproviders/{providerId}": {
      "get": {
        "tags": [
          "management",
          "cloud provider"
        ],
        "summary": "Get a cloud provider.",
        "description": "Get a cloud provider.",
        "operationId": "getCloudProvider",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "management",
          "cloud provider"
        ],
        "summary": "Update a cloud provider.",
        "description": "Update a cloud provider.",
        "operationId": "updateCloudProvider",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "management",
          "cloud provider"
        ],
        "summary": "Delete a cloud provider.",
        "description": "Delete a cloud provider.",
        "operationId": "deleteCloudProvider",
        "security": [
          {
            "petstore_auth": [
              "write:wisecost",
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/cloudproviders/{providerId}/connectivity": {
      "post": {
        "tags": [
          "management",
          "cloud provider",
          "connectivity"
        ],
        "summary": "test a connectivity of a new cloud provider, the cloud provider's config is not saved.",
        "description": "Test  a cloud provider.",
        "operationId": "testCloudProviderConnectivityOnTheFly",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "management",
          "cloud provider",
          "connectivity"
        ],
        "summary": "test a connectivity of a existing cloud provider.",
        "description": "Get a cloud provider.",
        "operationId": "testCloudProviderConnectivity",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/aliyun/regions": {
      "get": {
        "tags": [
          "management"
        ],
        "summary": "get regions of aliyun.",
        "description": "get regions of aliyun.",
        "operationId": "getAliyunRegions"
      }
    },
    "/management/import/aliyun/validateAccessToken": {
      "post": {
        "tags": [
          "management",
          "import"
        ],
        "summary": "validate a connectivity of a new cloud provider, the cloud provider's config is not saved.",
        "description": "Test  a cloud provider.",
        "operationId": "validateAccessToken",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/import/aliyun/managedClusters": {
      "post": {
        "tags": [
          "management",
          "import"
        ],
        "summary": "get managed kubernetes clusters of aliyun.",
        "description": "get managed kubernetes clusters of aliyun.",
        "operationId": "getAliyunManagedClusters",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/import/aliyun/kubeconfig": {
      "post": {
        "tags": [
          "management",
          "import"
        ],
        "summary": "get kubeconfig of a managed kubernetes cluster.",
        "description": "get kubeconfig of a managed kubernetes cluster.",
        "operationId": "getAliyunKubeConfig",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/import/aliyun/validateKubeconfig": {
      "post": {
        "tags": [
          "management",
          "import"
        ],
        "summary": "validate kubeconfig of a managed kubernetes cluster.",
        "description": "validate kubeconfig of a managed kubernetes cluster.",
        "operationId": "validateAliyunKubeConfig",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/import/aliyun/validatePrometheusConfig": {
      "post": {
        "tags": [
          "management",
          "import"
        ],
        "summary": "validate prometheus config of a managed kubernetes cluster.",
        "description": "validate prometheus config  of a managed kubernetes cluster.",
        "operationId": "validateAlibabaCloudPrometheusConfig",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/huaweicloud/regions": {
      "get": {
        "tags": [
          "management"
        ],
        "summary": "get regions of aliyun.",
        "description": "get regions of aliyun.",
        "operationId": "getHuaweiCloudRegions"
      }
    },
    "/management/import/huaweicloud/validateAccessToken": {
      "post": {
        "tags": [
          "management",
          "import"
        ],
        "summary": "validate a connectivity of a new cloud provider, the cloud provider's config is not saved.",
        "description": "Test  a cloud provider.",
        "operationId": "validateHuaweiCloudAccessToken",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/import/huaweicloud/managedClusters": {
      "post": {
        "tags": [
          "management",
          "import"
        ],
        "summary": "get managed kubernetes clusters of aliyun.",
        "description": "get managed kubernetes clusters of aliyun.",
        "operationId": "getHuaweiCloudManagedClusters",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/import/huaweicloud/kubeconfig": {
      "post": {
        "tags": [
          "management",
          "import"
        ],
        "summary": "get kubeconfig of a managed kubernetes cluster.",
        "description": "get kubeconfig of a managed kubernetes cluster.",
        "operationId": "getHuaweiCloudKubeConfig",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/import/huaweicloud/validateKubeconfig": {
      "post": {
        "tags": [
          "management",
          "import"
        ],
        "summary": "validate kubeconfig of a managed kubernetes cluster.",
        "description": "validate kubeconfig of a managed kubernetes cluster.",
        "operationId": "validateHuaweiCloudKubeConfig",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/management/import/huaweicloud/validatePrometheusConfig": {
      "post": {
        "tags": [
          "management",
          "import"
        ],
        "summary": "validate prometheus config of a managed kubernetes cluster.",
        "description": "validate prometheus config  of a managed kubernetes cluster.",
        "operationId": "validateHuaweiCloudPrometheusConfig",
        "security": [
          {
            "petstore_auth": [
              "read:wisecost"
            ]
          }
        ]
      }
    },
    "/version": {
      "get": {
        "tags": [
          "version"
        ],
        "description": "获取当前系统版本",
        "operationId": "getVersion"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "wisecost_auth": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://cost.wisecost.com/oauth/authorize",
            "scopes": {
              "write:wisecost": "write permission for wisecost",
              "read:wisecost": "read permission for wisecost",
              "admin:wisecost": "admin permission for wisecost"
            }
          }
        }
      },
      "api_key": {
        "type": "apiKey",
        "name": "api_key",
        "in": "header"
      }
    }
  }
}