---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: wiseinf-system
  labels:
    app: wisecost
data:
  default.conf: |-
      server {
        listen 80;

        location / {
          root /usr/share/nginx/html/;
          include /etc/nginx/mime.types;
          try_files $uri $uri/ /index.html;

          location /api/ {
            rewrite ^/api/(.*) /$1 break;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;

            proxy_pass http://localhost:7070;
          }
        }
      }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wisecost-conf
  namespace: wiseinf-system
  labels:
    app: wisecost
data:
  wisecost.yaml: |-
    server:
      port: 7070
      allowedOrigins:
      - "http://wisecost"
      - "https://wisecost"
      - "http://47.92.69.144"
    engine:
      defaultClusterId: default
      max_prometheus_query_duration: 1440m
      scrape_interval: 30s
      aggregate_labels:
        environment:
        - env
        product:
        - product
        application:
        - application
        - app
        department:
        - department
        team:
        - team
        - group
        owner:
        - owner
    optimize:
      dataSourceName: "wisecost:Wisecost~@tcp(mysql:3306)/wisecost?charset=utf8mb4&parseTime=true"
      maxOpenConns: 10
    storage:
      type: file
      parameters:
        path: "data/clusters.yaml"
        directory: "data/"
    kubestore:
      type: mysql
      parameters:
        dataSourceName: "wisecost:Wisecost~@tcp(mysql:3306)/storage?charset=utf8mb4&parseTime=true"
        maxOpenConns: 10

---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: wisecost
  name: wisecost
  namespace: wiseinf-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wisecost
  template:
    metadata:
      labels:
        app: wisecost
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 0
      containers:
        - name: wisecost-ui
          image: wiseinf/wisecost-ui:eebb346
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 500M
            limits:
              cpu: 1000m
              memory: 2G
        - name: wisecost
          image: wiseinf/wisecost:3f3e222
          command:
            - "/wisecost/wisecost"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: wisecost-data-volume
              mountPath: /wisecost/data
            - name: wisecost-logs-volume
              mountPath: /wisecost/logs
            - name: wisecost-conf-volume
              mountPath: /wisecost/conf
#              subPath: wisecost.yml
          ports:
            - containerPort: 7070
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 500M
            limits:
              cpu: 1000m
              memory: 2G
      volumes:
        # Config for wisecost-ui
        - name: nginx-config
          configMap:
            name: nginx-config
        # Configs for wisecost
        - name: wisecost-data-volume
          hostPath:
            path: /wisecost/data1
            type: DirectoryOrCreate
        - name: wisecost-logs-volume
          hostPath:
            path: /wisecost/logs
            type: DirectoryOrCreate
        - name: wisecost-conf-volume
          configMap:
            name: wisecost-conf
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: wisecost-ui
  name:  wisecost-ui-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wisecost
  type: NodePort